apiVersion: 1

datasources:
  - name: HistorianBridge
    type: yesoreyeram-infinity-datasource
    uid: historian-bridge
    access: proxy
    url: http://gateway:8080
    isDefault: true
    jsonData:
      auth_method: none
      global_queries: []
